# Generated by Django 4.2.29 on 2026-05-07 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('session_type', models.CharField(choices=[('socratic', 'Socratic'), ('game', 'Game'), ('quiz', 'Quiz'), ('code_review', 'Code Review'), ('interview', 'Interview')], max_length=20)),
                ('language', models.CharField(default='python', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('struggled_concepts', models.JSONField(default=list)),
                ('mastered_concepts', models.JSONField(default=list)),
                ('messages', models.JSONField(default=list)),
                ('performance_score', models.FloatField(null=True)),
                ('xp_earned', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MistakeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=50)),
                ('mistake_description', models.TextField()),
                ('student_answer', models.TextField()),
                ('correct_answer', models.TextField()),
                ('source', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo_sessions.learningsession')),
            ],
        ),
    ]
