# Generated by Django 4.2.29 on 2026-05-11 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algo_sessions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistakerecord',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='algo_sessions.learningsession'),
        ),
    ]
