# Generated by Django 4.2.29 on 2026-05-11 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=255, unique=True)),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('chunk_type', models.CharField(choices=[('concept', 'Concept Explanation'), ('code', 'Code Example'), ('steps', 'Algorithm Steps'), ('diagram', 'Diagram/Visualization'), ('misconception', 'Common Misconception')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('source', models.CharField(default='gfg', max_length=100)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MistakeDNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominant_pattern', models.CharField(max_length=100)),
                ('cross_topic', models.BooleanField(default=False)),
                ('evidence', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_dna', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mistake DNA Records',
            },
        ),
    ]
