# Generated by Django 4.2.29 on 2026-05-08 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('total_score', models.IntegerField(default=10)),
                ('progress_type', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('code_practice', 'Code Practice')], max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConceptMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=50)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('weak', 'Weak'), ('learning', 'Learning'), ('mastered', 'Mastered')], default='weak', max_length=20)),
                ('times_practiced', models.IntegerField(default=0)),
                ('times_wrong', models.IntegerField(default=0)),
                ('persistent_weakness', models.BooleanField(default=False)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'concept_name')},
            },
        ),
    ]
