# Generated by Django 4.2.29 on 2026-05-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_userprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
