# Generated by Django 4.2.29 on 2026-05-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_active_delete_conceptmastery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('concept', models.CharField(max_length=100)),
                ('quiz_taken', models.BooleanField(default=False)),
                ('quiz_score', models.FloatField(default=0.0)),
                ('mistakes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user_id', 'concept')},
            },
        ),
    ]
